const layout = {
  space: {
    paragraph: 20,
    elements: 40,
    container: 80,
  },
  columns: {
    oneColumn: {
      xs: { span: 21 },
      sm: { span: 21 },
      md: { span: 21 },
      lg: { span: 21 },
      xl: { span: 21 },
      xxl: { span: 21 },
    },
    twoColumns: {
      xs: { span: 10 },
      sm: { span: 10 },
      md: { span: 8 },
      lg: { span: 8 },
      xl: { span: 8 },
      xxl: { span: 8 },
    },
    twoColumnImg: {
      xs: { span: 18, order: 1 },
      sm: { span: 13, order: 1 },
      md: { span: 9, order: 1 },
      lg: { span: 9, order: 1 },
      xl: { span: 8, order: 1 },
      xxl: { span: 8, order: 1 },
    },
    twoColumnTxt: {
      xs: { span: 21, order: 0 },
      sm: { span: 21, order: 0 },
      md: { span: 12, order: 0 },
      lg: { span: 12, order: 0 },
      xl: { span: 13, order: 0 },
      xxl: { span: 13, order: 0 },
    },
    twoColumnInfo: {
      xs: { span: 21, order: 1 },
      sm: { span: 18, order: 1 },
      md: { span: 14, order: 1 },
      lg: { span: 5 },
      xl: { span: 5 },
      xxl: { span: 5 },
    },
    twoColumnInfoText: {
      xs: { span: 21, order: 0 },
      sm: { span: 21, order: 0 },
      md: { span: 21, order: 0 },
      lg: { span: 13, order: 1 },
      xl: { span: 13, order: 1 },
      xxl: { span: 13, order: 1 },
    },

    threeColumns: {
      xs: { span: 21 },
      sm: { span: 21 },
      md: { span: 13 },
      lg: { span: 7 },
      xl: { span: 7 },
      xxl: { span: 7 },
    },
    fourColumns: {
      xs: { span: 21 },
      sm: { span: 21 },
      md: { span: 12 },
      lg: { span: 6 },
      xl: { span: 6 },
      xxl: { span: 6 },
    },
  },
  imageSize: { xs: { span: 18 }, sm: { span: 18 } },
};
export default layout;
