import imageProfile1 from '../../assets/images/mockPersonas/student-1.jpg';
import imageProfile2 from '../../assets/images/mockPersonas/student-2.jpg';
import imageProfile3 from '../../assets/images/mockPersonas/student-3.jpg';

const mockSeed = [
  {
    id: '1',
    name: 'Lucas de Moraes',
    age: '22',
    pronoun: 'Ele/Dele',
    description:
      'Na primeira mentoria eu não sabia quem eu era, definir meus sonhos ou para onde eu estava indo. Ter a oportunidade de ser mentorada no primeiro semestre da minha (tão sonhada) faculdade fez total diferença. Hoje, sinto que me conheço mais, sei como e o que estou fazendo para alcançar meus sonhos.',
    college: 'USP - Universidade de São Paulo',
    course: 'Engenharia Mecatrônica',
    imageProfile: imageProfile1,
    linkedin: 'https://www.linkedin.com/in/lucas-de-moraes-mata/',
    email: 'tech@isemear.org.br',
    whatsapp: '5511982778267',
    invitedDate: Date.parse('2022-03-17T14:48:00'),
    isConfirmed: false,
    isRejected: false,
    isExperired: false,
    acceptedDate: Date.parse('2001-01-01T00:00:00'),
    finalDate: Date.parse('2001-01-01T00:00:00'),
    rejectedDate: Date.parse('2001-01-01T00:00:00'),
    project: 'PlantYou',
    isFeedbackAnswered: false,
    mentoringHappened: false,
  },
  {
    id: '2',
    name: 'Jéssica Gonsalves',
    age: '22',
    pronoun: 'Ela/Dela',
    description:
      'Ser mentoranda me permitiu tomar consciência do meu próprio protagonismo e em como consigo pontencializá-lo na minha jornada. Mais do que isso, me permitiu construir em conjunto com a minha mentora, um processo sistêmico de reflexão, concepção e tomada de decisões.',
    college: 'USP - Universidade de São Paulo',
    course: 'Engenharia Elétrica',
    imageProfile: imageProfile2,
    linkedin: 'https://www.linkedin.com/in/gonsalvesjessica/',
    email: 'tech@isemear.org.br',
    whatsapp: '5511982778267',
    invitedDate: Date.parse('2022-03-07T14:48:00'),
    isConfirmed: false,
    isRejected: false,
    isExperired: false,
    acceptedDate: Date.parse('2001-01-01T00:00:00'),
    finalDate: Date.parse('2001-01-01T00:00:00'),
    rejectedDate: Date.parse('2001-01-01T00:00:00'),
    project: 'Pontapé Empreendedor',
    isFeedbackAnswered: true,
    mentoringHappened: true,
  },
  {
    id: '3',
    name: 'Gabriela Rodrigues',
    age: '21',
    pronoun: 'Ela/Dela',
    description:
      'A oportunidade de poder me conectar através das mentorias com pessoas já ambientadas no mercado de trabalho vêm trazendo diversos benefícios, e principalmente, auxiliando no meu autoconhecimento',
    linkedin: 'https://www.linkedin.com/in/gabriela-rodrigues-matias/',
    college: 'Inteli - Instituto de Tecnologia e Liderança',
    course: 'Engenharia de Computação',
    imageProfile: imageProfile3,
    email: 'tech@isemear.org.br',
    whatsapp: '5511982778267',
    invitedDate: Date.parse('2022-02-22T14:48:00'),
    isConfirmed: false,
    isRejected: false,
    isExperired: false,
    acceptedDate: Date.parse('2001-01-01T00:00:00'),
    finalDate: Date.parse('2001-01-01T00:00:00'),
    rejectedDate: Date.parse('2001-01-01T00:00:00'),
    project: 'Programa de Carreira',
    isFeedbackAnswered: false,
    mentoringHappened: false,
  },
];
export default mockSeed;
