import React, { Fragment, useState } from 'react';
import Image from 'next/image';
import { Col, Row, Select, Input } from 'antd';

const countriesList = [
  {
    country: 'Afeganistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/23px-Flag_of_Afghanistan.svg.png',
    ddi: 93,
    continente: 'Asia',
  },
  {
    country: 'Africa do Sul',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/23px-Flag_of_South_Africa.svg.png',
    ddi: 27,
    continente: 'Africa',
  },
  {
    country: 'Albania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/21px-Flag_of_Albania.svg.png',
    ddi: 355,
    continente: 'Europa',
  },
  {
    country: 'Alemanha',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png',
    ddi: 49,
    continente: 'Europa',
  },
  {
    country: 'Andorra',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png',
    ddi: 376,
    continente: 'Europa',
  },
  {
    country: 'Angola',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/23px-Flag_of_Angola.svg.png',
    ddi: 244,
    continente: 'Africa',
  },
  {
    country: 'Anguilla',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/23px-Flag_of_Anguilla.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Ant\u00edgua e Barbuda',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/23px-Flag_of_Antigua_and_Barbuda.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Antilhas Holandesas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_Netherlands_Antilles_%281986%E2%80%932010%29.svg/23px-Flag_of_the_Netherlands_Antilles_%281986%E2%80%932010%29.svg.png',
    ddi: 599,
    continente: 'America Central',
  },
  {
    country: 'Arabia Saudita',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png',
    ddi: 966,
    continente: 'Asia',
  },
  {
    country: 'Argelia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/23px-Flag_of_Algeria.svg.png',
    ddi: 213,
    continente: 'Africa',
  },
  {
    country: 'Argentina',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png',
    ddi: 54,
    continente: 'America do Sul',
  },
  {
    country: 'Armenia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/23px-Flag_of_Armenia.svg.png',
    ddi: 374,
    continente: 'Asia',
  },
  {
    country: 'Aruba',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/23px-Flag_of_Aruba.svg.png',
    ddi: 297,
    continente: 'America Central',
  },
  {
    country: 'Australia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/23px-Flag_of_Australia.svg.png',
    ddi: 61,
    continente: 'Oceania',
  },
  {
    country: 'Austria',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/23px-Flag_of_Austria.svg.png',
    ddi: 43,
    continente: 'Europa',
  },
  {
    country: 'Azerbaijao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/23px-Flag_of_Azerbaijan.svg.png',
    ddi: 994,
    continente: 'Asia',
  },
  {
    country: 'Bahamas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/77/Bahamas_Flag.svg/23px-Bahamas_Flag.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Bangladesh',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png',
    ddi: 880,
    continente: 'Asia',
  },
  {
    country: 'Barbados',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/23px-Flag_of_Barbados.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Bahrein',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/23px-Flag_of_Bahrain.svg.png',
    ddi: 973,
    continente: 'Asia',
  },
  {
    country: 'Belgica',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/23px-Flag_of_Belgium_%28civil%29.svg.png',
    ddi: 32,
    continente: 'Europa',
  },
  {
    country: 'Belize',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/23px-Flag_of_Belize.svg.png',
    ddi: 501,
    continente: 'America Central',
  },
  {
    country: 'Benim',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/23px-Flag_of_Benin.svg.png',
    ddi: 229,
    continente: 'Africa',
  },
  {
    country: 'Bermudas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/23px-Flag_of_Bermuda.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Bielorr\u00fassia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/23px-Flag_of_Belarus.svg.png',
    ddi: 375,
    continente: 'Europa',
  },
  {
    country: 'Bol\u00edvia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/22px-Flag_of_Bolivia.svg.png',
    ddi: 591,
    continente: 'America do Sul',
  },
  {
    country: 'B\u00f3snia e Herzegovina',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/23px-Flag_of_Bosnia_and_Herzegovina.svg.png',
    ddi: 387,
    continente: 'Europa',
  },
  {
    country: 'Botswana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/23px-Flag_of_Botswana.svg.png',
    ddi: 267,
    continente: 'Africa',
  },
  {
    country: 'Brasil',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png',
    ddi: 55,
    continente: 'America do Sul',
  },
  {
    country: 'Brunei',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/23px-Flag_of_Brunei.svg.png',
    ddi: 673,
    continente: 'Asia',
  },
  {
    country: 'Bulgaria',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png',
    ddi: 359,
    continente: 'Europa',
  },
  {
    country: 'Burkina Faso',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/23px-Flag_of_Burkina_Faso.svg.png',
    ddi: 226,
    continente: 'Africa',
  },
  {
    country: 'Burundi',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png',
    ddi: 257,
    continente: 'Africa',
  },
  {
    country: 'Butao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/23px-Flag_of_Bhutan.svg.png',
    ddi: 975,
    continente: 'Asia',
  },
  {
    country: 'Cabo Verde',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/23px-Flag_of_Cape_Verde.svg.png',
    ddi: 238,
    continente: 'Africa',
  },
  {
    country: 'Camar\u00f5es',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/23px-Flag_of_Cameroon.svg.png',
    ddi: 237,
    continente: 'Africa',
  },
  {
    country: 'Camboja',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/23px-Flag_of_Cambodia.svg.png',
    ddi: 855,
    continente: 'Asia',
  },
  {
    country: 'Canada',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.png',
    ddi: 1,
    continente: 'America do Norte',
  },
  {
    country: 'Cazaquistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/23px-Flag_of_Kazakhstan.svg.png',
    ddi: 7,
    continente: 'Asia',
  },
  {
    country: 'Chade',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/23px-Flag_of_Chad.svg.png',
    ddi: 235,
    continente: 'Africa',
  },
  {
    country: 'Chile',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/23px-Flag_of_Chile.svg.png',
    ddi: 56,
    continente: 'America do Sul',
  },
  {
    country: 'Rep\u00fablica Popular da China',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png',
    ddi: 86,
    continente: 'Asia',
  },
  {
    country: 'Chipre',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/23px-Flag_of_Cyprus.svg.png',
    ddi: 357,
    continente: 'Europa',
  },
  {
    country: 'Col\u00f4mbia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/23px-Flag_of_Colombia.svg.png',
    ddi: 57,
    continente: 'America do Sul',
  },
  {
    country: 'Comores',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/23px-Flag_of_the_Comoros.svg.png',
    ddi: 269,
    continente: 'Africa',
  },
  {
    country: 'CongoBrazzaville',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/23px-Flag_of_the_Republic_of_the_Congo.svg.png',
    ddi: 242,
    continente: 'Africa',
  },
  {
    country: 'CongoKinshasa',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png',
    ddi: 243,
    continente: 'Africa',
  },
  {
    country: 'Coreia do Norte',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/23px-Flag_of_North_Korea.svg.png',
    ddi: 850,
    continente: 'Asia',
  },
  {
    country: 'Coreia do Sul',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png',
    ddi: 82,
    continente: 'Asia',
  },
  {
    country: 'Costa do Marfim',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/23px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png',
    ddi: 225,
    continente: 'Africa',
  },
  {
    country: 'Costa Rica',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/23px-Flag_of_Costa_Rica.svg.png',
    ddi: 506,
    continente: 'America Central',
  },
  {
    country: 'Croacia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/23px-Flag_of_Croatia.svg.png',
    ddi: 385,
    continente: 'Europa',
  },
  {
    country: 'Cuba',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/23px-Flag_of_Cuba.svg.png',
    ddi: 53,
    continente: 'America Central',
  },
  {
    country: 'Dinamarca',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png',
    ddi: 45,
    continente: 'Europa',
  },
  {
    country: 'Djibuti',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/23px-Flag_of_Djibouti.svg.png',
    ddi: 253,
    continente: 'Africa',
  },
  {
    country: 'Dominica',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/23px-Flag_of_Dominica.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Egipto',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png',
    ddi: 20,
    continente: 'Africa/Asia',
  },
  {
    country: 'El Salvador',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/23px-Flag_of_El_Salvador.svg.png',
    ddi: 503,
    continente: 'America Central',
  },
  {
    country: 'Emirados \u00c1rabes Unidos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/23px-Flag_of_the_United_Arab_Emirates.svg.png',
    ddi: 971,
    continente: 'Asia',
  },
  {
    country: 'Equador',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/23px-Flag_of_Ecuador.svg.png',
    ddi: 593,
    continente: 'America do Sul',
  },
  {
    country: 'Eritreia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/23px-Flag_of_Eritrea.svg.png',
    ddi: 291,
    continente: 'Africa',
  },
  {
    country: 'Eslovaquia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/23px-Flag_of_Slovakia.svg.png',
    ddi: 421,
    continente: 'Europa',
  },
  {
    country: 'Eslovenia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/23px-Flag_of_Slovenia.svg.png',
    ddi: 386,
    continente: 'Europa',
  },
  {
    country: 'Espanha',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/23px-Flag_of_Spain.svg.png',
    ddi: 34,
    continente: 'Europa',
  },
  {
    country: 'Estados Unidos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png',
    ddi: 1,
    continente: 'America do Norte',
  },
  {
    country: 'Est\u00f3nia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/23px-Flag_of_Estonia.svg.png',
    ddi: 372,
    continente: 'Europa',
  },
  {
    country: 'Eti\u00f3pia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/23px-Flag_of_Ethiopia.svg.png',
    ddi: 251,
    continente: 'Africa',
  },
  {
    country: 'Fiji',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/23px-Flag_of_Fiji.svg.png',
    ddi: 679,
    continente: 'Oceania',
  },
  {
    country: 'Filipinas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.png',
    ddi: 63,
    continente: 'Asia',
  },
  {
    country: 'Finlandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/23px-Flag_of_Finland.svg.png',
    ddi: 358,
    continente: 'Europa',
  },
  {
    country: 'Franca',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 33,
    continente: 'Europa',
  },
  {
    country: 'Gabao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/20px-Flag_of_Gabon.svg.png',
    ddi: 241,
    continente: 'Africa',
  },
  {
    country: 'Gambia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/23px-Flag_of_The_Gambia.svg.png',
    ddi: 220,
    continente: 'Africa',
  },
  {
    country: 'Gana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/23px-Flag_of_Ghana.svg.png',
    ddi: 233,
    continente: 'Africa',
  },
  {
    country: 'Ge\u00f3rgia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/23px-Flag_of_Georgia.svg.png',
    ddi: 995,
    continente: 'Asia',
  },
  {
    country: 'Gibraltar',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/23px-Flag_of_Gibraltar.svg.png',
    ddi: 350,
    continente: 'Europa',
  },
  {
    country: 'Granada',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/23px-Flag_of_Grenada.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Grecia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png',
    ddi: 30,
    continente: 'Europa',
  },
  {
    country: 'Groenlandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/23px-Flag_of_Greenland.svg.png',
    ddi: 299,
    continente: 'America do Norte',
  },
  {
    country: 'Guadalupe',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 590,
    continente: 'America Central',
  },
  {
    country: 'Guam',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/23px-Flag_of_Guam.svg.png',
    ddi: 1,
    continente: 'Oceania',
  },
  {
    country: 'Guatemala',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/23px-Flag_of_Guatemala.svg.png',
    ddi: 502,
    continente: 'America Central',
  },
  {
    country: 'Guiana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/23px-Flag_of_Guyana.svg.png',
    ddi: 592,
    continente: 'America do Sul',
  },
  {
    country: 'Guiana Francesa',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_French_Guiana.svg/23px-Flag_of_French_Guiana.svg.png',
    ddi: 594,
    continente: 'America do Sul',
  },
  {
    country: 'Guine',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/23px-Flag_of_Guinea.svg.png',
    ddi: 224,
    continente: 'Africa',
  },
  {
    country: 'GuineBissau',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/23px-Flag_of_Guinea-Bissau.svg.png',
    ddi: 245,
    continente: 'Africa',
  },
  {
    country: 'Guine Equatorial',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/23px-Flag_of_Equatorial_Guinea.svg.png',
    ddi: 240,
    continente: 'Africa',
  },
  {
    country: 'Haiti',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/23px-Flag_of_Haiti.svg.png',
    ddi: 509,
    continente: 'America Central',
  },
  {
    country: 'Honduras',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Honduras_%282008_Olympics%29.svg/23px-Flag_of_Honduras_%282008_Olympics%29.svg.png',
    ddi: 504,
    continente: 'America Central',
  },
  {
    country: 'Hong Kong',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/23px-Flag_of_Hong_Kong.svg.png',
    ddi: 852,
    continente: 'Asia',
  },
  {
    country: 'Hungria',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.png',
    ddi: 36,
    continente: 'Europa',
  },
  {
    country: 'Iemen',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/23px-Flag_of_Yemen.svg.png',
    ddi: 967,
    continente: 'Asia',
  },
  {
    country: 'Ilhas Cayman',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/23px-Flag_of_the_Cayman_Islands.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Ilha Christmas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/23px-Flag_of_Christmas_Island.svg.png',
    ddi: 672,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Cocos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/23px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png',
    ddi: 672,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Cook',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/23px-Flag_of_the_Cook_Islands.svg.png',
    ddi: 682,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Feroe',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/21px-Flag_of_the_Faroe_Islands.svg.png',
    ddi: 298,
    continente: 'Europa',
  },
  {
    country: 'Ilha Heard e Ilhas McDonald',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/23px-Flag_of_Australia.svg.png',
    ddi: 672,
    continente: 'Oceania',
  },
  {
    country: 'Maldivas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/23px-Flag_of_Maldives.svg.png',
    ddi: 960,
    continente: 'Asia',
  },
  {
    country: 'Ilhas Malvinas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/23px-Flag_of_the_Falkland_Islands.svg.png',
    ddi: 500,
    continente: 'America do Sul',
  },
  {
    country: 'Ilhas Marianas do Norte',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/23px-Flag_of_the_Northern_Mariana_Islands.svg.png',
    ddi: 1,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Marshall',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/23px-Flag_of_the_Marshall_Islands.svg.png',
    ddi: 692,
    continente: 'Oceania',
  },
  {
    country: 'Ilha Norfolk',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/23px-Flag_of_Norfolk_Island.svg.png',
    ddi: 672,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Salomao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/23px-Flag_of_the_Solomon_Islands.svg.png',
    ddi: 677,
    continente: 'Oceania',
  },
  {
    country: 'Ilhas Virgens Americanas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/23px-Flag_of_the_United_States_Virgin_Islands.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Ilhas Virgens Britanicas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/23px-Flag_of_the_British_Virgin_Islands.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: '\u00cdndia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
    ddi: 91,
    continente: 'Asia',
  },
  {
    country: 'Indonesia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png',
    ddi: 62,
    continente: 'Asia/Oceania',
  },
  {
    country: 'Ira',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png',
    ddi: 98,
    continente: 'Asia',
  },
  {
    country: 'Iraque',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/23px-Flag_of_Iraq.svg.png',
    ddi: 964,
    continente: 'Asia',
  },
  {
    country: 'Irlanda',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/23px-Flag_of_Ireland.svg.png',
    ddi: 353,
    continente: 'Europa',
  },
  {
    country: 'Islandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/21px-Flag_of_Iceland.svg.png',
    ddi: 354,
    continente: 'Europa',
  },
  {
    country: 'Israel',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/21px-Flag_of_Israel.svg.png',
    ddi: 972,
    continente: 'Asia',
  },
  {
    country: 'Italia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/23px-Flag_of_Italy.svg.png',
    ddi: 39,
    continente: 'Europa',
  },
  {
    country: 'Jamaica',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/23px-Flag_of_Jamaica.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Japao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png',
    ddi: 81,
    continente: 'Asia',
  },
  {
    country: 'Jordania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/23px-Flag_of_Jordan.svg.png',
    ddi: 962,
    continente: 'Asia',
  },
  {
    country: 'Kiribati',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/23px-Flag_of_Kiribati.svg.png',
    ddi: 686,
    continente: 'Oceania',
  },
  {
    country: 'Kosovo',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Flag_of_Kosovo.svg/21px-Flag_of_Kosovo.svg.png',
    ddi: 383,
    continente: 'Europa',
  },
  {
    country: 'Kuwait',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/23px-Flag_of_Kuwait.svg.png',
    ddi: 965,
    continente: 'Asia',
  },
  {
    country: 'Laos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/23px-Flag_of_Laos.svg.png',
    ddi: 856,
    continente: 'Asia',
  },
  {
    country: 'Lesoto',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/23px-Flag_of_Lesotho.svg.png',
    ddi: 266,
    continente: 'Africa',
  },
  {
    country: 'Let\u00f4nia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/23px-Flag_of_Latvia.svg.png',
    ddi: 371,
    continente: 'Europa',
  },
  {
    country: 'L\u00edbano',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png',
    ddi: 961,
    continente: 'Asia',
  },
  {
    country: 'Liberia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/23px-Flag_of_Liberia.svg.png',
    ddi: 231,
    continente: 'Africa',
  },
  {
    country: 'L\u00edbia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/23px-Flag_of_Libya.svg.png',
    ddi: 218,
    continente: 'Africa',
  },
  {
    country: 'Liechtenstein',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/23px-Flag_of_Liechtenstein.svg.png',
    ddi: 423,
    continente: 'Europa',
  },
  {
    country: 'Lituania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/23px-Flag_of_Lithuania.svg.png',
    ddi: 370,
    continente: 'Europa',
  },
  {
    country: 'Luxemburgo',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/23px-Flag_of_Luxembourg.svg.png',
    ddi: 352,
    continente: 'Europa',
  },
  {
    country: 'Macau',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/23px-Flag_of_Macau.svg.png',
    ddi: 853,
    continente: 'Asia',
  },
  {
    country: 'Rep\u00fablica da Maced\u00f4nia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/23px-Flag_of_North_Macedonia.svg.png',
    ddi: 389,
    continente: 'Europa',
  },
  {
    country: 'Madagascar',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/23px-Flag_of_Madagascar.svg.png',
    ddi: 261,
    continente: 'Africa',
  },
  {
    country: 'Malasia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/23px-Flag_of_Malaysia.svg.png',
    ddi: 60,
    continente: 'Asia',
  },
  {
    country: 'Malawi',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/23px-Flag_of_Malawi.svg.png',
    ddi: 265,
    continente: 'Africa',
  },
  {
    country: 'Mali',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/23px-Flag_of_Mali.svg.png',
    ddi: 223,
    continente: 'Africa',
  },
  {
    country: 'Malta',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/23px-Flag_of_Malta.svg.png',
    ddi: 356,
    continente: 'Europa',
  },
  {
    country: 'Marrocos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/23px-Flag_of_Morocco.svg.png',
    ddi: 212,
    continente: 'Africa',
  },
  {
    country: 'Martinica',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 596,
    continente: 'America Central',
  },
  {
    country: 'Maur\u00edcia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/23px-Flag_of_Mauritius.svg.png',
    ddi: 230,
    continente: 'Africa',
  },
  {
    country: 'Mauritania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/23px-Flag_of_Mauritania.svg.png',
    ddi: 222,
    continente: 'Africa',
  },
  {
    country: 'Mayotte',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 269,
    continente: 'Africa',
  },
  {
    country: 'Mexico',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png',
    ddi: 52,
    continente: 'America do Norte',
  },
  {
    country: 'Estados Federados da Micronesia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/23px-Flag_of_the_Federated_States_of_Micronesia.svg.png',
    ddi: 691,
    continente: 'Oceania',
  },
  {
    country: 'Mocambique',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/23px-Flag_of_Mozambique.svg.png',
    ddi: 258,
    continente: 'Africa',
  },
  {
    country: 'Moldavia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/23px-Flag_of_Moldova.svg.png',
    ddi: 373,
    continente: 'Europa',
  },
  {
    country: 'M\u00f4naco',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/19px-Flag_of_Monaco.svg.png',
    ddi: 377,
    continente: 'Europa',
  },
  {
    country: 'Mong\u00f3lia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/23px-Flag_of_Mongolia.svg.png',
    ddi: 976,
    continente: 'Asia',
  },
  {
    country: 'Montenegro',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/23px-Flag_of_Montenegro.svg.png',
    ddi: 382,
    continente: 'Europa',
  },
  {
    country: 'Montserrat',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/23px-Flag_of_Montserrat.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Myanmar',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/23px-Flag_of_Myanmar.svg.png',
    ddi: 95,
    continente: 'Asia',
  },
  {
    country: 'Nam\u00edbia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/23px-Flag_of_Namibia.svg.png',
    ddi: 264,
    continente: 'Africa',
  },
  {
    country: 'Nauru',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/23px-Flag_of_Nauru.svg.png',
    ddi: 674,
    continente: 'Oceania',
  },
  {
    country: 'Nepal',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/12px-Flag_of_Nepal.svg.png',
    ddi: 977,
    continente: 'Asia',
  },
  {
    country: 'Nicaragua',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/23px-Flag_of_Nicaragua.svg.png',
    ddi: 505,
    continente: 'America Central',
  },
  {
    country: 'N\u00edger',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/18px-Flag_of_Niger.svg.png',
    ddi: 227,
    continente: 'Africa',
  },
  {
    country: 'Nigeria',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png',
    ddi: 234,
    continente: 'Africa',
  },
  {
    country: 'Niue',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/23px-Flag_of_Niue.svg.png',
    ddi: 683,
    continente: 'Oceania',
  },
  {
    country: 'Noruega',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png',
    ddi: 47,
    continente: 'Europa',
  },
  {
    country: 'Nova Caled\u00f4nia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/40px-Flags_of_New_Caledonia.svg.png',
    ddi: 687,
    continente: 'Oceania',
  },
  {
    country: 'Nova Zelandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/23px-Flag_of_New_Zealand.svg.png',
    ddi: 64,
    continente: 'Oceania',
  },
  {
    country: 'Oma',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/23px-Flag_of_Oman.svg.png',
    ddi: 968,
    continente: 'Asia',
  },
  {
    country: 'Pa\u00edses Baixos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png',
    ddi: 31,
    continente: 'Europa',
  },
  {
    country: 'Palau',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/23px-Flag_of_Palau.svg.png',
    ddi: 680,
    continente: 'Oceania',
  },
  {
    country: 'Palestina',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png',
    ddi: 970,
    continente: 'Asia',
  },
  {
    country: 'Panama',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/23px-Flag_of_Panama.svg.png',
    ddi: 507,
    continente: 'America Central',
  },
  {
    country: 'PapuaNova Guine',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/20px-Flag_of_Papua_New_Guinea.svg.png',
    ddi: 675,
    continente: 'Oceania',
  },
  {
    country: 'Paquistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png',
    ddi: 92,
    continente: 'Asia',
  },
  {
    country: 'Paraguai',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/23px-Flag_of_Paraguay.svg.png',
    ddi: 595,
    continente: 'America do Sul',
  },
  {
    country: 'Peru',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/23px-Flag_of_Peru.svg.png',
    ddi: 51,
    continente: 'America do Sul',
  },
  {
    country: 'Polinesia Francesa',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/23px-Flag_of_French_Polynesia.svg.png',
    ddi: 689,
    continente: 'Oceania',
  },
  {
    country: 'Pol\u00f4nia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png',
    ddi: 48,
    continente: 'Europa',
  },
  {
    country: 'Porto Rico',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/23px-Flag_of_Puerto_Rico.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Portugal',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/23px-Flag_of_Portugal.svg.png',
    ddi: 351,
    continente: 'Europa',
  },
  {
    country: 'Qatar',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/23px-Flag_of_Qatar.svg.png',
    ddi: 974,
    continente: 'Asia',
  },
  {
    country: 'Quenia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/23px-Flag_of_Kenya.svg.png',
    ddi: 254,
    continente: 'Africa',
  },
  {
    country: 'Quirguistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/23px-Flag_of_Kyrgyzstan.svg.png',
    ddi: 996,
    continente: 'Asia',
  },
  {
    country: 'Reino Unido',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png',
    ddi: 44,
    continente: 'Europa',
  },
  {
    country: 'Rep\u00fablica CentroAfricana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/23px-Flag_of_the_Central_African_Republic.svg.png',
    ddi: 236,
    continente: 'Africa',
  },
  {
    country: 'Rep\u00fablica Dominicana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/23px-Flag_of_the_Dominican_Republic.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Rep\u00fablica Tcheca',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/23px-Flag_of_the_Czech_Republic.svg.png',
    ddi: 420,
    continente: 'Europa',
  },
  {
    country: 'Reuniao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 262,
    continente: 'Africa',
  },
  {
    country: 'Romenia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png',
    ddi: 40,
    continente: 'Europa',
  },
  {
    country: 'Ruanda',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png',
    ddi: 250,
    continente: 'Africa',
  },
  {
    country: 'R\u00fassia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png',
    ddi: 7,
    continente: 'Europa/Asia',
  },
  {
    country: 'Saara Ocidental',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/23px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png',
    ddi: 212,
    continente: 'Africa',
  },
  {
    country: 'Samoa',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/23px-Flag_of_Samoa.svg.png',
    ddi: 685,
    continente: 'Oceania',
  },
  {
    country: 'Samoa Americana',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/23px-Flag_of_American_Samoa.svg.png',
    ddi: 1,
    continente: 'Oceania',
  },
  {
    country: 'Santa Helena territ\u00f3rio',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/23px-Flag_of_Saint_Helena.svg.png',
    ddi: 290,
    continente: 'Africa',
  },
  {
    country: 'Santa L\u00facia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/23px-Flag_of_Saint_Lucia.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Sao Crist\u00f3vao e Nevis',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/23px-Flag_of_Saint_Kitts_and_Nevis.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Sao Marinho',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/20px-Flag_of_San_Marino.svg.png',
    ddi: 378,
    continente: 'Europa',
  },
  {
    country: 'SaintPierre e Miquelon',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 508,
    continente: 'America do Norte',
  },
  {
    country: 'Sao Tome e Pr\u00edncipe',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/23px-Flag_of_Sao_Tome_and_Principe.svg.png',
    ddi: 239,
    continente: 'Africa',
  },
  {
    country: 'Sao Vicente e Granadinas',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/23px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Seicheles',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/23px-Flag_of_Seychelles.svg.png',
    ddi: 248,
    continente: 'Africa',
  },
  {
    country: 'Senegal',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/23px-Flag_of_Senegal.svg.png',
    ddi: 221,
    continente: 'Africa',
  },
  {
    country: 'Serra Leoa',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/23px-Flag_of_Sierra_Leone.svg.png',
    ddi: 232,
    continente: 'Africa',
  },
  {
    country: 'Servia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/23px-Flag_of_Serbia.svg.png',
    ddi: 381,
    continente: 'Europa',
  },
  {
    country: 'Singapura',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png',
    ddi: 65,
    continente: 'Asia',
  },
  {
    country: 'S\u00edria',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/23px-Flag_of_Syria.svg.png',
    ddi: 963,
    continente: 'Asia',
  },
  {
    country: 'Somalia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/23px-Flag_of_Somalia.svg.png',
    ddi: 252,
    continente: 'Africa',
  },
  {
    country: 'Sri Lanka',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/23px-Flag_of_Sri_Lanka.svg.png',
    ddi: 94,
    continente: 'Asia',
  },
  {
    country: 'Suazilandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/23px-Flag_of_Eswatini.svg.png',
    ddi: 268,
    continente: 'Africa',
  },
  {
    country: 'Sudao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/23px-Flag_of_Sudan.svg.png',
    ddi: 249,
    continente: 'Africa',
  },
  {
    country: 'Sudao do Sul',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/23px-Flag_of_South_Sudan.svg.png',
    ddi: 211,
    continente: 'Africa',
  },
  {
    country: 'Suecia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/23px-Flag_of_Sweden.svg.png',
    ddi: 46,
    continente: 'Europa',
  },
  {
    country: 'Su\u00edca',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png',
    ddi: 41,
    continente: 'Europa',
  },
  {
    country: 'Suriname',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/23px-Flag_of_Suriname.svg.png',
    ddi: 597,
    continente: 'America do Sul',
  },
  {
    country: 'Tadjiquistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/23px-Flag_of_Tajikistan.svg.png',
    ddi: 992,
    continente: 'Asia',
  },
  {
    country: 'Tailandia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.png',
    ddi: 66,
    continente: 'Asia',
  },
  {
    country: 'Rep\u00fablica da China',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png',
    ddi: 886,
    continente: 'Asia',
  },
  {
    country: 'Tanzania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/23px-Flag_of_Tanzania.svg.png',
    ddi: 255,
    continente: 'Africa',
  },
  {
    country: 'Territ\u00f3rio Britanico do Oceano \u00cdndico',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg/23px-Flag_of_the_Commissioner_of_the_British_Indian_Ocean_Territory.svg.png',
    ddi: 246,
    continente: 'Africa',
  },
  {
    country: 'TimorLeste',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/23px-Flag_of_East_Timor.svg.png',
    ddi: 670,
    continente: 'Asia',
  },
  {
    country: 'Togo',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/23px-Flag_of_Togo.svg.png',
    ddi: 228,
    continente: 'Africa',
  },
  {
    country: 'Tokelau',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/23px-Flag_of_Tokelau.svg.png',
    ddi: 690,
    continente: 'Oceania',
  },
  {
    country: 'Tonga',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/23px-Flag_of_Tonga.svg.png',
    ddi: 676,
    continente: 'Oceania',
  },
  {
    country: 'Trinidad e Tobago',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/23px-Flag_of_Trinidad_and_Tobago.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Tun\u00edsia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/23px-Flag_of_Tunisia.svg.png',
    ddi: 216,
    continente: 'Africa',
  },
  {
    country: 'Turcas e Caicos',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/23px-Flag_of_the_Turks_and_Caicos_Islands.svg.png',
    ddi: 1,
    continente: 'America Central',
  },
  {
    country: 'Turquemenistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/23px-Flag_of_Turkmenistan.svg.png',
    ddi: 993,
    continente: 'Asia',
  },
  {
    country: 'Turquia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png',
    ddi: 90,
    continente: 'Asia//Europa',
  },
  {
    country: 'Tuvalu',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/23px-Flag_of_Tuvalu.svg.png',
    ddi: 688,
    continente: 'Oceania',
  },
  {
    country: 'Ucrania',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/23px-Flag_of_Ukraine.svg.png',
    ddi: 380,
    continente: 'Europa',
  },
  {
    country: 'Uganda',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/23px-Flag_of_Uganda.svg.png',
    ddi: 256,
    continente: 'Africa',
  },
  {
    country: 'Uruguai',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/23px-Flag_of_Uruguay.svg.png',
    ddi: 598,
    continente: 'America do Sul',
  },
  {
    country: 'Uzbequistao',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/23px-Flag_of_Uzbekistan.svg.png',
    ddi: 998,
    continente: 'Asia',
  },
  {
    country: 'Vanuatu',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/23px-Flag_of_Vanuatu.svg.png',
    ddi: 678,
    continente: 'Oceania',
  },
  {
    country: 'Vaticano',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/15px-Flag_of_the_Vatican_City.svg.png',
    ddi: 379,
    continente: 'Europa',
  },
  {
    country: 'Venezuela',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/23px-Flag_of_Venezuela.svg.png',
    ddi: 58,
    continente: 'America do Sul',
  },
  {
    country: 'Vietna',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.png',
    ddi: 84,
    continente: 'Asia',
  },
  {
    country: 'Wallis e Futuna',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
    ddi: 681,
    continente: 'Oceania',
  },
  {
    country: 'Zambia',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/23px-Flag_of_Zambia.svg.png',
    ddi: 260,
    continente: 'Africa',
  },
  {
    country: 'Zimbabue',
    img: 'https:////upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/23px-Flag_of_Zimbabwe.svg.png',
    ddi: 263,
    continente: 'Africa',
  },
];

const countryOptions = () => {
  const regexWord = '[a-zA-Z]';
  const size = 7;
  const [ddi, setDdi] = useState(55);
  const onSearch = (value) => {
    countriesList.filter((item) => (item.country.includes(value) ? true : false));
    console.log('search:', value);
  };
  const infoList = (item) => {
    return (
      <Fragment>
        <Image
          src={item.img}
          alt={`Bandeira do ${item.country}`}
          width={3 * size}
          height={2 * size}
        />
        {` +${item.ddi}`}
      </Fragment>
    );
  };

  return (
    <Input
      addonBefore={
        <Select
          defaultValue={55}
          onChange={(value) => setDdi(value)}
          style={{ width: '120px' }}
          showSearch
        >
          {countriesList.map((item, index) => (
            <Select.Option value={item.ddi} key={`country-${index}`}>
              {infoList(item)}
            </Select.Option>
          ))}
        </Select>
      }
    />
  );
};
export default countryOptions;


