const SubareasList = [
  { value: 'Administração de empresas' },
  { value: 'Administração de operações e produções' },
  { value: 'Administração estratégica' },
  { value: 'Administração financeira' },
  { value: 'Agronomia' },
  { value: 'Análise ambiental' },
  { value: 'Análise e desenvolvimento de sistemas' },
  { value: 'Analista de computação científica' },
  { value: 'Analista de Processamento de dados' },
  { value: 'Analista de sistemas de informação' },
  { value: 'Analista de sistemas e tecnologia da informação' },
  { value: 'Analista de sistemas' },
  { value: 'Analista de telecomunicações' },
  { value: 'Analista informática biomédica' },
  { value: 'Antropologia' },
  { value: 'Arqueologia' },
  { value: 'Arquitetura e urbanismo' },
  { value: 'Arquivologia' },
  { value: 'Artes cênicas' },
  { value: 'Artes plásticas' },
  { value: 'Assessor de imprensa' },
  { value: 'Astrônomia' },
  { value: 'Audiovisual' },
  { value: 'Biblioteconomia' },
  { value: 'Bioengenharia' },
  { value: 'Biologia marinha' },
  { value: 'Biologia' },
  { value: 'Biomedicina' },
  { value: 'Ciências ambientais' },
  { value: 'Ciências contábeis' },
  { value: 'Ciências da computação' },
  { value: 'Ciências políticas' },
  { value: 'Ciências físicq e biomolecular' },
  { value: 'Ciência molecular' },
  { value: 'Ciência na área de tecnologia' },
  { value: 'Ciência natural' },
  { value: 'Ciência químicq e farmacêuticq' },
  { value: 'Cinema' },
  { value: 'Consultoria' },
  { value: 'Cuidador de idosos' },
  { value: 'Dança' },
  { value: 'Desenho industrial' },
  { value: 'Design de interiores' },
  { value: 'Design de jogos' },
  { value: 'Design gráfico' },
  { value: 'Direito ambiental' },
  { value: 'Direito' },
  { value: 'Ecologia' },
  { value: 'Economia' },
  { value: 'Editor' },
  { value: 'Educação física' },
  { value: 'Enfermagem' },
  { value: 'Engenharia aeroespacial' },
  { value: 'Engenharia agrícola' },
  { value: 'Engenharia agrônomica' },
  { value: 'Engenharia ambiental' },
  { value: 'Engenharia biomédica' },
  { value: 'Engenharia biotecnológica' },
  { value: 'Engenharia cartográfica' },
  { value: 'Engenharia civil' },
  { value: 'Engenharia da aeronáutica' },
  { value: 'Engenharia da qualidade' },
  { value: 'Engenharia de agrimensura' },
  { value: 'Engenharia de alimentos' },
  { value: 'Engenharia de aquicultura' },
  { value: 'Engenharia de áudio' },
  { value: 'Engenharia de bioprocessos' },
  { value: 'Engenharia de computação' },
  { value: 'Engenharia de controle e automação' },
  { value: 'Engenharia de energia' },
  { value: 'Engenharia de gestão' },
  { value: 'Engenharia de informação' },
  { value: 'Engenharia de instrumentação, automação e robótica' },
  { value: 'Engenharia de manufatura' },
  { value: 'Engenharia de manutenção' },
  { value: 'Engenharia de materiais' },
  { value: 'Engenharia de minas' },
  { value: 'Engenharia de pesca' },
  { value: 'Engenharia de petróleo' },
  { value: 'Engenharia de produção' },
  { value: 'Engenharia de serviços' },
  { value: 'Engenharia de sistemas e informática' },
  { value: 'Engenharia de sistemas eletrônicos' },
  { value: 'Engenharia de software' },
  { value: 'Engenharia de tecidos' },
  { value: 'Engenharia de telecomunicações' },
  { value: 'Engenharia de transportes' },
  { value: 'Engenharia econômica' },
  { value: 'Engenharia elétrica' },
  { value: 'Engenharia eletrônica' },
  { value: 'Engenharia estrutural' },
  { value: 'Engenharia física' },
  { value: 'Engenharia florestal' },
  { value: 'Engenharia geográfica' },
  { value: 'Engenharia geológica' },
  { value: 'Engenharia hidráulica' },
  { value: 'Engenharia industrial madeireiro' },
  { value: 'Engenharia industrial' },
  { value: 'Engenharia mecânica' },
  { value: 'Engenharia mecatrônica' },
  { value: 'Engenharia metalúrgica' },
  { value: 'Engenharia militar' },
  { value: 'Engenharia multimídia' },
  { value: 'Engenharia naval e oceânica' },
  { value: 'Engenharia nuclear' },
  { value: 'Engenharia óptica' },
  { value: 'Engenharia química' },
  { value: 'Engenharia têxtil.' },
  { value: 'Estatística' },
  { value: 'Estética e cosmetologia' },
  { value: 'Farmácia' },
  { value: 'Filosofia' },
  { value: 'Física' },
  { value: 'Física computacional' },
  { value: 'Física médica' },
  { value: 'Física na área biológica' },
  { value: 'Fisioterapia' },
  { value: 'Fonoaudiologia' },
  { value: 'Fotografia' },
  { value: 'Geofísica' },
  { value: 'Geografia' },
  { value: 'Geólogia' },
  { value: 'Gerontologia' },
  { value: 'Gestão da informação' },
  { value: 'Gestão de responsabilidade' },
  { value: 'Gestão' },
  { value: 'História' },
  { value: 'Jornalismo' },
  { value: 'Letras' },
  { value: 'Linguística' },
  { value: 'Logística' },
  { value: 'Marketing de influência' },
  { value: 'Marketing digital' },
  { value: 'Marketing offline' },
  { value: 'Marketing socioambiental' },
  { value: 'Marketing' },
  { value: 'Massoterapia' },
  { value: 'Matemática' },
  { value: 'Matemática computacional' },
  { value: 'Medicina veterinária' },
  { value: 'Medicina' },
  { value: 'Meteorologia' },
  { value: 'Meteorologista' },
  { value: 'Moda' },
  { value: 'Música.' },
  { value: 'Musicoterapia' },
  { value: 'Nanotecnologia' },
  { value: 'Nutrição' },
  { value: 'Oceanografia' },
  { value: 'Oceanógrafo' },
  { value: 'Odontologia' },
  { value: 'Pedagogia' },
  { value: 'Produção cultural' },
  { value: 'Produção editorial' },
  { value: 'Protética' },
  { value: 'Psicologia' },
  { value: 'Publicidade e propaganda' },
  { value: 'Publicitário' },
  { value: 'Química' },
  { value: 'Química ambiental' },
  { value: 'Química industrial' },
  { value: 'Quiropraxia' },
  { value: 'Rádio e TV' },
  { value: 'Radiologia' },
  { value: 'Recursos Humanos' },
  { value: 'Redator' },
  { value: 'Relações internacionais' },
  { value: 'Relações públicas e relacionamento com o cliente.' },
  { value: 'Revisor' },
  { value: 'Secretariado executivo' },
  { value: 'Secretariado' },
  { value: 'Serviço social' },
  { value: 'Sistemas de informação' },
  { value: 'Sociologia.' },
  { value: 'Terapia ocupacional.' },
  { value: 'Tradução e interpretação.' },
  { value: 'Webdesign.' },
  { value: 'Zootecnia.' },
];

export default SubareasList;
